language: php
php:
    - 7.1
    - 7.2

dist: trusty

sudo: false

cache:
    directories:
        - ~/.composer/cache

install:
    - composer update --no-interaction --prefer-dist ${COMPOSER_FLAGS}

script:
    - composer validate --strict
    - composer fix-style
    - composer analyse
    - composer test
